version: '3'
services:
  mysql:
    image: mysql:5.5
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
  app:
    build: .
    depends_on:
      - mysql
    ports:
      - "9090:9090"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password